import { agentId, BANKS, EXPERIMENT_ID, json, MONTHS, realTs, round, SEAT_BASE, SEATS, type BankDef, type Insert, type Seat } from "./common";

const NAMES: Record<BankDef["bankId"], Record<Seat, [string, string]>> = {
  calder_ridge: {
    coo_chair: ["Margaret Ellison", "Chief Operating Officer"],
    cio: ["Devin Okafor", "Chief Information Officer"],
    ciso: ["Rachel Brandt", "Chief Information Security Officer"],
    general_counsel: ["Thomas Whitfield", "General Counsel"],
    cro: ["Priya Raman", "Chief Risk Officer"],
    cfo: ["Gordon Liu", "Chief Financial Officer"],
    head_consumer_lending: ["Carla Mendes", "EVP, Consumer Lending"],
    head_marketing: ["Jason Pruitt", "SVP, Marketing"],
  },
  tollgate: {
    coo_chair: ["Walter Haines", "Chief Operating Officer"],
    cio: ["Nina Castellanos", "Chief Information Officer"],
    ciso: ["Sam Adeyemi", "Chief Information Security Officer"],
    general_counsel: ["Elaine Porter", "General Counsel"],
    cro: ["Marcus Webb", "Chief Risk Officer"],
    cfo: ["Diane Kowalski", "Chief Financial Officer"],
    head_consumer_lending: ["Tyler Brooks", "EVP, Consumer Lending"],
    head_marketing: ["Ashley Moreno", "SVP, Marketing"],
  },
};

export function agentName(bank: BankDef, seat: Seat): string {
  return NAMES[bank.bankId][seat][0];
}

/** Tollgate's CISO is replaced from 2027-03 onward. */
export function activeAgent(bank: BankDef, seat: Seat, month: string): string {
  return isReplacement(bank, seat, month) ? agentId(bank, seat, 2) : agentId(bank, seat);
}

export function activeName(bank: BankDef, seat: Seat, month: string): string {
  return isReplacement(bank, seat, month) ? "Lauren Fisk" : agentName(bank, seat);
}

function isReplacement(bank: BankDef, seat: Seat, month: string): boolean {
  return bank.bankId === "tollgate" && seat === "ciso" && month >= "2027-03";
}

export function baseline(bank: BankDef, seat: Seat): number {
  return round(SEAT_BASE[seat] + bank.stanceShift, 2);
}

export function seedPeople(insert: Insert): void {
  insert("experiments", {
    experiment_id: EXPERIMENT_ID,
    name: "DEV FIXTURE - pilot shape (not real data)",
    notes: "Generated by dashboard/scripts/seed-dev.ts for local UI development. Values are invented.",
    created_at: realTs(0),
  });

  for (const bank of BANKS) {
    insert("runs", {
      run_id: bank.runId,
      experiment_id: EXPERIMENT_ID,
      bank_id: bank.bankId,
      condition: bank.condition,
      replicate: 1,
      seed: 424242,
      parent_run_id: null,
      fork_month: null,
      model_versions: json({ committee: "claude-sonnet-4-6", classifier: "claude-haiku-4-5", estimator: "claude-sonnet-4-6" }),
      config_hash: "devfixture0000000000000000000000",
      start_month: MONTHS[0],
      current_month: MONTHS[2],
      status: bank.status,
      spend_cap_usd_per_month: bank.bankId === "tollgate" ? 60 : 50,
      started_at: realTs(0, 5),
    });

    for (const seat of SEATS) {
      const [name, title] = NAMES[bank.bankId][seat];
      const replaced = bank.bankId === "tollgate" && seat === "ciso";
      insert("agents", {
        agent_id: agentId(bank, seat),
        run_id: bank.runId,
        bank_id: bank.bankId,
        seat,
        name,
        title,
        persona_file: `config/personas/${bank.bankId}/${seat}.md`,
        active_from: MONTHS[0],
        active_to: replaced ? MONTHS[1] : null,
        stance_baseline: baseline(bank, seat),
        replaced_agent_id: null,
        replacement_reason: null,
      });
    }
  }

  const tollgate = BANKS[1]!;
  insert("agents", {
    agent_id: agentId(tollgate, "ciso", 2),
    run_id: tollgate.runId,
    bank_id: tollgate.bankId,
    seat: "ciso",
    name: "Lauren Fisk",
    title: "Chief Information Security Officer",
    persona_file: "config/personas/tollgate/ciso_2.md",
    active_from: MONTHS[2],
    active_to: null,
    stance_baseline: 2.3,
    replaced_agent_id: agentId(tollgate, "ciso"),
    replacement_reason: "Board replaced the CISO after the customer data exposure in the chat pilot.",
  });

  for (const bank of BANKS) {
    for (const month of MONTHS) {
      for (const seat of SEATS) {
        insert("agent_memories", {
          run_id: bank.runId,
          agent_id: activeAgent(bank, seat, month),
          sim_month: month,
          text: `${activeName(bank, seat, month)} notes for ${month}: priorities, open commitments, and concerns from the committee meeting.`,
          token_estimate: 380 + SEATS.indexOf(seat) * 41,
          compressed: month === MONTHS[2] ? 1 : 0,
        });
      }
    }
  }
}
